env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - jest
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  lines-around-comment:
    - error
    -
      beforeBlockComment: true
      afterBlockComment: true
      beforeLineComment: true
      afterLineComment: true
      allowBlockStart: true
      allowBlockEnd: true
      allowObjectStart: true
      allowObjectEnd: true
      allowArrayStart: true
      allowArrayEnd: true
  max-len:
      - error
      - { "code": 80, "ignoreUrls": true }
  no-confusing-arrow:
    - error
  no-mixed-operators: error
  no-unexpected-multiline: error
  curly:
    - error
    - all
